### ISSUE TITLE
Support for Laravel 6

### ISSUE THREAD

**Issue by eyounelson** [bosunski/lpaystack#7]
Currently, this package does not support the latest versions of Laravel 6.

Attempting to require this package in a Laravel 6 install will result in composer error, similar to below:

`Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Conclusion: install xeviant/paystack 0.5
    - Installation request for xeviant/laravel-paystack ^1.5 -> satisfiable by xeviant/laravel-paystack[1.5, 1.5.1].
    - Conclusion: remove laravel/framework v6.4.0
    - Conclusion: don't install laravel/framework v6.4.0
    - xeviant/paystack 0.5 requires illuminate/container ^5.7 -> satisfiable by illuminate/container[5.7.17, 5.7.18, 5.7.19, 5.7.x-dev, 5.8.x-dev, v5.7.0, v5.7.1, v5.7.10, v5.7.11, v5.7.15, v5.7.2, v5.7.20, v5.7.21, v5.7.22, v5.7.23, v5.7.26, v5.7.27, v5.7.28, v5.7.3, v5.7.4, v5.7.5, v5.7.6, v5.7.7, v5.7.8, v5.7.9, v5.8.0, v5.8.11, v5.8.12, v5.8.14, v5.8.15, v5.8.17, v5.8.18, v5.8.19, v5.8.2, v5.8.20, v5.8.22, v5.8.24, v5.8.27, v5.8.28, v5.8.29, v5.8.3, v5.8.30, v5.8.31, v5.8.32, v5.8.33, v5.8.34, v5.8.35, v5.8.4, v5.8.8, v5.8.9].
`

**Comment by bosunski** [comment]
Thanks, @emmannl, I'll look into this and get back here.

**Comment by bosunski** [comment]
@emmannl can you run `composer require xeviant/laravel-paystack:^1.5.2` and see if that works?

I'll be expecting your feedback. Thanks. 🙌

**Comment by eyounelson** [comment]
It works now.

great work...
